export enum ShippingCountry{
ÅLAND = "Åland Islands",
/*AFGANISTAN,
ALBANIA,
ALGERIA,
AMERICAN_SAMOA,
ANDORRA,
ANGOLA,
ANGUILLA,
ANTARCTICA,
ANTIGUA_AND_BARBUDA,
ARGENTINA,
ARMENIA,
ARUBA, */
AUSTRALIA = "Australia",
AUSTRIA = "Austria",
AZERBAIJAN = "Azerbaijan",
BAHAMAS = "Bahamas",
BAHRAIN = "Bahrain",
BANGLADESH = "Bangladesh"

}